spring.application.name=SecureVault

securevault.jwt.secret=${SECUREVAULT_JWT_SECRET}

spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/securevault}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.client=TRACE
logging.level.org.springframework.security.oauth2.core=TRACE

securevault.aes.key=${SECUREVAULT_AES_KEY}
securevault.aes.original-key=${SECUREVAULT_AES_ORIGINAL_KEY:}
securevault.aes.legacy-key=${SECUREVAULT_AES_LEGACY_KEY:}

# Google OAuth2

spring.security.oauth2.client.registration.google.client-id=776844671403-0r1eo9d7ik6k45a6va5odhk43hirvmis.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.registration.google.provider=google
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# Redis

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Redis Cache

spring.cache.type=redis
spring.cache.redis.time-to-live=300000

# Gmail SMTP

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
